version: '3.8'

services:
  db:
    image: postgres:17.5
    container_name: psql
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: lapudai
    volumes:
      - ./psql_data:/var/lib/postgresql/data
      - ./lapudai.sql:/docker-entrypoint-initdb.d/lapudai.sql
    ports:
      - "5433:5432"
      
  bot:
    build: .
    container_name: bot
    command: python /app/backend/main.py
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./log.txt:/app/log.txt
      - ./backend/users.db:/app/backend/users.db